Update snarkos_setup.yml (#60)
In the main (2nd) call to `tx-cannon batch-execute`: 
`--repeat` --> `--repetitions`.
Also increased the number to `9000001` so it would
not run out over a long test.
The symptom of the previous command is a log entry
that starts with
```
error: unexpected argument '--repeat' found
```
and there is no actual execution of the test transactions!

Signed-off-by: Eric McCarthy <7607035+bendyarm@users.noreply.github.com>